<?php

namespace App\Utilities\CreationalGeneral;

class Door extends MapSite
{

    private Room $_room1;
    private Room $_room2;
    private bool $_is_open;

    public function __construct(Room $room1, Room $room2)
    {
        $this->_room1 = $room1;
        $this->_room2 = $room2;
    }

    public function enter()
    {
        parent::enter(); // TODO: Change the autogenerated stub
    }

    public function otherSideFrom(Room $room) : Room
    {

    }

}
